Added ajaxified likes, comments, and follow requests to project
brvarner/photogram-ajax pull request #1
Opened 2024-07-10 14:56 UTC by brvarner

2024-07-10 16:20 UTC, rayguna approved these changes

2024-07-10 16:20 UTC, rayguna commented on app/views/follow_requests/create.js.erb
Nice use of variables makes the code easier to read.

2024-07-10 16:20 UTC, rayguna commented on app/views/likes/create.js.erb
Nice use of variables enhances code readability.

2024-07-10 16:20 UTC, rayguna commented on app/views/likes/destroy.js.erb
Consistently using variables for code readability.

2024-07-10 20:02 UTC, ahuynh3a requested changes
Great job Brandon! Overall. I think you did a great job! Could you make some changes to your follow_request/create.js.erb file and I can approve after!

2024-07-10 20:02 UTC, ahuynh3a commented on app/views/follow_requests/create.js.erb
This is an interesting approach! Another way to create follow request is to replace the classesDiv with the _follow_unfollow.html.erb template passing in sender and recipient so that way you don't have to create another file!

2024-07-10 20:02 UTC, ahuynh3a commented on app/views/follow_requests/destroy.js.erb
This is great! Can you try to apply it to your follow_requests/create.js.erb?

2024-07-10 20:02 UTC, ahuynh3a commented on app/views/likes/_form.html.erb
> +<%= form_with(model: like, local: false, class: "d-inline-block") do |form| %>
Good job being mindful of when to use local: false and remote: true!

2024-07-10 20:02 UTC, ahuynh3a commented on app/views/likes/create.js.erb
> +var existingLikes = $("#<%= dom_id(@like.photo) %>_likes");
I love how clear your code is!

2024-07-12 14:07 UTC, brvarner commented on app/views/follow_requests/destroy.js.erb
Hey Annie! Can do!

2024-07-12 14:34 UTC, ahuynh3a approved these changes
Great job Brandon! Thank you for making the adjustments!

2024-07-12 17:57 UTC, merged